<a href="https://colab.research.google.com/github/kartech-dev/clgPy/blob/main/assign9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy
numpy.__version__

import numpy as np

In [3]:
#Write a program to create a 1D NumPy array of numbers from 1 to 10 and print it.
import numpy as np
array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Create a 3X3 array of zeros and a 2Ö 4 array of ones. Print both arrays.
import numpy as np
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3,3))
print(zeros_array)
print(ones_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Create a NumPy array containing numbers from 5 to 50 with a step size of 5 and print it.
import numpy as np
array = np.arange(5, 51, 5)
print(array)

In [ ]:
#Create an array of numbers 112 and reshape it into a 3Ö 4 matrix and print it.
import numpy as np
array = np.arange(112).reshape(3, 4)
print(array)


In [ ]:
#Create two array of same size and compute addition, subtraction, multiplication and division of these arrays and print the results.
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2
print(addition)
print(subtraction)
print(multiplication)
print(division)



In [ ]:
#Create a 1D array from 10 to 100 with step 10, and print: First three elements, Last three elements, Every second element
import numpy as np
array = np.arange(10, 101, 10)
print(array[:3])
print(array[-3:])
print(array[::2])

[10 20 30]
[ 80  90 100]
[10 30 50 70 90]


In [ ]:
#Create a NumPy array of numbers 120. Extract all elements divisible by 3.
import numpy as np
array = np.arange(120)
divisible_by_3 = array[array % 3 == 0]
print(divisible_by_3)

In [5]:
#Given an array of random integers between 1100 (size 10), compute: Mean , Median, Standard deviation.
array=np.random.randint(1100,size=10)
print(array)
mean=np.mean(array)
print(mean)
median=np.median(array)
print(median)
std=np.std(array)
print(std)

[ 990  488  919 1054   14 1035  918  141  351    1]
591.1
703.0
416.7681489749427


In [6]:
#Create two 2X3 arrays and stack them vertically and horizontally.
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
vertical_stack=np.vstack((array1,array2))
horizontal_stack=np.hstack((array1,array2))
print(vertical_stack)
print(horizontal_stack)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [7]:
#Create a 4X4 matrix of random numbers, and subtract the mean of each column from its column value.
array=np.random.randint(100,size=(4,4))
print(array)
mean=np.mean(array,axis=0)
print(mean)
subtracted_array=array-mean
print(subtracted_array)


[[22  3 85 46]
 [22 89 54 27]
 [85 45 68  2]
 [29 56  1 47]]
[39.5  48.25 52.   30.5 ]
[[-17.5  -45.25  33.    15.5 ]
 [-17.5   40.75   2.    -3.5 ]
 [ 45.5   -3.25  16.   -28.5 ]
 [-10.5    7.75 -51.    16.5 ]]


In [8]:
#Create two random matrices A (3X2) and B (2X4). Compute their product using np.dot() and verify the shape of the result.
array1=np.random.randint(10,size=(3,2))
array2=np.random.randint(10,size=(2,4))
product=np.dot(array1,array2)
print(product)
print(product.shape)


[[ 8  8  8 22]
 [36  8 36 71]
 [32  8 32 64]]
(3, 4)


In [9]:
#Solve the following system using np.linalg.solve():2x + y = 5, x y = 1.
A=np.array([[2,1],[1,1]])
b=np.array([5,1])
x=np.linalg.solve(A,b)
print(x)


[ 4. -3.]


In [10]:
#Create a NumPy array of 20 random integers (1100). Replace all elements greater than 50 with 50, and all elements less than 20 with 20. Print the modified array.
arr=np.random.randint(1100,size=20)
print("Original array:\n", arr)

# Replace elements greater than 50 with 50
arr[arr > 50] = 50

# Replace elements less than 20 with 20
arr[arr < 20] = 20

print("Modified array:\n", arr)

Original array:
 [ 339  331  545  476  480  161   58  814  634  624  297   57  440 1094
  485  342  153  738  392  415]
Modified array:
 [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]


In [11]:
#Create a 6Ö 6 array with values from 1 to 36. Perform the following: Reshape into 6X6 matrix Extract the border elements into a separate array Set all border elements in the original matrix to 0 Print the nal modi ed matrix.
array=np.arange(1,37).reshape(6,6)
print(array)
border_elements=array[0,0],array[0,5],array[5,0],array[5,5]
print(border_elements)
array[0,:]=0
array[5,:]=0
array[:,0]=0
array[:,5]=0
print(array)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
(np.int64(1), np.int64(6), np.int64(31), np.int64(36))
[[ 0  0  0  0  0  0]
 [ 0  8  9 10 11  0]
 [ 0 14 15 16 17  0]
 [ 0 20 21 22 23  0]
 [ 0 26 27 28 29  0]
 [ 0  0  0  0  0  0]]


In [ ]:
#Given two NumPy arrays representing coordinates of points: p1 = np.array([2, 3]) p2 = np.array([10, 8]) Compute the Euclidean distance between them using vectorized NumPy operations.
